# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Model\ProjectRepository:
        alias: App\Adapter\Persistence\Postgres\PdoProjectRepository
        public: false

    App\Model\HealthSnapshotStore:
        alias: App\Adapter\Persistence\Postgres\PdoHealthSnapshotStore
        public: false

    App\Model\MetricStore:
        alias: App\Adapter\Persistence\Postgres\PdoMetricStore
        public: false

    App\Model\HealthProbe:
        alias: App\Adapter\Probe\HttpHealthProbe
        public: false

    App\Model\LogSource:
        alias: App\Adapter\Logs\RenderLogSource
        public: false
